ReplAsyncExecutor: pass self as an arg instead of via stack frame locals (#56)
* ReplAsyncExecutor: pass self as an arg instead of via stack frame locals

This has several benefits:
- It is more reliable in cases when [inspect.stack raises IndexError].
- It is more reliable in cases when, somehow, the jishaku module has no attribute 'repl'.
- It is less magic and easier to reason about and unserstand.

[inspect.stack raises IndexError]: https://bugs.python.org/issue1628987

* incorporate suggestions from review (#56)

jishaku.repl.scope:
- Bring back get_parent_var and get_parent_scope_from_var since they may be useful outside of jishaku
- Bring back test cases for this

jishaku.repl.compilation.py:
Remove the try-except NameError from CORO_CODE. ReplAsyncExecutor always passes this now so it doesn't make sense.